### ISSUE TITLE
Rose 4.1 Doesn’t Work

### ISSUE THREAD

**Issue by herrkugla** [Litteeen/Rose#11]
Installed Rose 4.1 with Cephei 1.4 and Rocketbootstrap 1.07 beta 3 and nothing works. Tried disabling the tweak and re-enable it and still nothing. Tried uninstalling and used iCleaner, then reinstalled and didn’t work. I have an iPhone X on iOS 13.3 with Checkra1n 0.9.7.

**Comment by OngoGablogian** [comment]
Having the same issue. iPhone X 13.3

**Comment by Litteeen** [comment]
Could you both provide me a screenshot of your settings? And check if the sh.litten.rosepreferences.plist file is in the folder /var/mobile/Library/Preferences, if not please also mention that ^^

**Comment by Litteeen** [comment]
Oh and also, have you installed the Rose built with the identifier sh.litten.rose?

**Comment by OngoGablogian** [comment]
![FE017202-5E93-44FD-A0D4-AC88EDDDF3FB](https://user-images.githubusercontent.com/18250317/71927440-54e73180-314a-11ea-98f5-c8f5d3aff771.jpeg)

Only other option I have enabled is feedback on typing. Also the bundle identifier is correct and plist file is in the location mentioned.

**Comment by herrkugla** [comment]
The file is in the correct location, bundle id is also correct. I have the tweak enabled with Taptic Engine, keyboard, volume change, and Enter Passcode enabled. Also tried turning them on individually but no luck.

**Comment by Litteeen** [comment]
Coule you try to uninstall Rose, delete the preferences file with filza, run icleaner, and install again?

**Comment by herrkugla** [comment]
Just gave it a try, enabled it, turned on Taptics and Volume Changes and still doesn’t work.

**Comment by OngoGablogian** [comment]
Didn’t seem to fix the issue for me either

**Comment by Litteeen** [comment]
Hiya!~ i think i’ve found the issue, please check in 5 minutes 😊

**Comment by herrkugla** [comment]
Works perfectly now! Thanks!

**Comment by OngoGablogian** [comment]
Yup, that seems to have fixed the issue for me. Thank you so much!

**Comment by Litteeen** [comment]
Glad to hear it, i will close this issue now, have a great day 💗
