### ISSUE TITLE
Touch feedback Anywhere blocks homescreen

### ISSUE THREAD

**Issue by Daniichan702** [Litteeen/Rose#12]
When enabling feedback for touches anywhere, the home screen no longer registers touch for opening apps or changing the page. The dock still works though (have FloatingDockPlus13 installed)

iPhone X - iOS 13.3

**Comment by Litteeen** [comment]
do you have xenhtml installed

**Comment by Daniichan702** [comment]
That’d be correct. I removed Xen and it’s working correctly. That’s unfortunate.
Thanks~
