### ISSUE TITLE
App launch

### ISSUE THREAD

**Issue by kailixs** [Litteeen/Rose#13]
All apps take noticeably longer to load when Rose tweak is enabled/installed

**Comment by Litteeen** [comment]
Could you test this build and tell me if it improves the app launches?

https://workupload.com/file/UbHbzCnX

**Comment by kailixs** [comment]
Yep, app launching is much faster now, thank you!

On 18 Mar 2020, at 16:20, Litten <notifications@github.com> wrote:

﻿

Could you test this build and tell me if it improves the app launches?

https://workupload.com/file/UbHbzCnX

**Comment by Litteeen** [comment]
Wait really? For me and one other person it didn’t really work out really good, still looking around

**Comment by kailixs** [comment]
Compared to the last version of Rose I used yes, apps open faster. Before it was noticeably slow.

On 18 Mar 2020, at 20:11, Litten <notifications@github.com> wrote:

﻿

Wait really? For me and one other person it didn’t really work out really good, still looking around

**Comment by Litteeen** [comment]
just keep in mind that this is a beta release ^^

**Comment by Litteeen** [comment]
The performance in the next version was  strongly increased, should be ready very soon that’s why I’ll close this now, just keep an eye out for the new version 😊

**Comment by kailixs** [comment]
Cool, thanks man

On 21 Mar 2020, at 23:53, Litten <notifications@github.com> wrote:

﻿

The performance in the next version was strongly increased, should be ready very soon that’s why I’ll close this now, just keep an eye out for the new version 😊
