### ISSUE TITLE
Not working inside any apps

### ISSUE THREAD

**Issue by JellyPeixe** [Litteeen/Rose#14]
Hello, I’ve bem using Rose for some weeks now and today (March 2nd) Rose stopped working inside any apps, it only works at home screen and inside Zebra package manager. I don’t know what happened and I can’t find a solution. I’m using iPhone XS Max iOS 13.3

**Comment by Litteeen** [comment]
Already tried 5.0? Maybe resetting the preferences will work

**Comment by JellyPeixe** [comment]
> Already tried 5.0? Maybe resetting the preferences will work

Yes, I just updated to 5.0. You didn’t beautiful job on this version of Rose, sadly, resetting the preferences and reinstalling the tweak didn’t work. I’m wondering if this can be related to another tweak compatibility issue.

**Comment by Litteeen** [comment]
Maybe you have disabled tweak injection with choicy 🤷🏼‍♀️

**Comment by JellyPeixe** [comment]
> Maybe you have disabled tweak injection with choicy 🤷🏼‍♀️

Sadly no, I was removing some not frequently used tweaks and one of them was choicy. Even without this tweak the issue persists... I think I’ll have to uninstall one tweak by one to see if there’s a compatibility issue.

**Comment by Litteeen** [comment]
You can just disable all tweaks with icleaner pro to see which one is causing it

**Comment by JellyPeixe** [comment]
> You can just disable all tweaks with icleaner pro to see which one is causing it

Ok, I’ll try that, thanks!

**Comment by JellyPeixe** [comment]
> You can just disable all tweaks with icleaner pro to see which one is causing it

Whoa, I found out that Rose was causing iCleaner Pro to crash... Now I can open iCleaner pro flawlessly. I’ll try to remove iCleaner and installing Rose to see if there’s a compatibility error that causes Rose not to function properly

**Comment by JellyPeixe** [comment]
> > You can just disable all tweaks with icleaner pro to see which one is causing it
> 
> Whoa, I found out that Rose was causing iCleaner Pro to crash... Now I can open iCleaner pro flawlessly. I’ll try to remove iCleaner and installing Rose to see if there’s a compatibility error that causes Rose not to function properly

Although uninstalling Rose fixes iCleaner Pro, uninstalling iCleaner doesn’t fix Rose

**Comment by Litteeen** [comment]
I also can’t fix any issues which i don’t have, neither my testers

**Comment by JellyPeixe** [comment]
> I also can’t fix any issues which i don’t have, neither my testers

Oh, ok. Thanks for spending your time trying to help me tough :)

**Comment by JellyPeixe** [comment]
> I also can’t fix any issues which i don’t have, neither my testers

I don’t know if this will help you but I found out that the keyboard press feedback works only on certain applications like the settings app, zebra and the homescreen search bar. I’ve installed other tweaks that has that same keyboard feedback feature and found out that they share the same issue of only working on zebra and homescreen.

**Comment by JellyPeixe** [comment]
Found out the issue, it’s Magma Evo that is causinha compatibility issues, disabling it causes Rose to work flawlessly. I’m closing the issue now.
