### ISSUE TITLE
5.0 killed Rose

### ISSUE THREAD

**Issue by Skyature** [Litteeen/Rose#16]
So...I just updated to 5.0 from 4.0. The tweak completely stopped working. Tried respringing. Resetting preferences. Repringing after turning the settings on. Uninstalling and reinstalling. NOTHING WORKS. Any way to fix this? Maybe you could put in a patch or smth? Thanks

Somewhere in the world
Skyature

**Comment by Litteeen** [comment]
I bet you just haven’t enabled the first switch in each sub menu

**Comment by Skyature** [comment]
Well, I did. It still doesn’t work. Now what do I do?

**Comment by Skyature** [comment]
Oh yep. My bad😅. There wasn’t an issue after all

**Comment by Litteeen** [comment]
Hehe i knew it, no worries 😊 closing this issue now
