### ISSUE TITLE
SpringBoard crash when toggling DND from CC

### ISSUE THREAD

**Issue by nyuszika7h** [Litteeen/Rose#19]
It seems like Rose sometimes randomly causes SpringBoard to crash when I toggle Do Not Disturb from the control center. (If it doesn’t crash, try toggling it several times in a row quickly.) I do not have haptic feedback enabled there, only for the keyboard.

Settings:
- Use Taptic Engine
- Anywhere -> Typing

Crash log: https://x0.at/mhv.txt

**Comment by Litteeen** [comment]
5.0.2 should fix the issue 😊
