### ISSUE TITLE
No feedback on call connect and haptic animations don’t work too

### ISSUE THREAD

**Issue by simba4** [Litteeen/Rose#21]

**Comment by Litteeen** [comment]
The haptics animation works fine for sure if you have an i7 or newer on iOS 13.0+, also enable the lock feedback 😊

Will test the call feedback ^^

**Comment by simba4** [comment]
What exactly the haptic animation is? 

Best regards,

Simeon Sheev

**Comment by Litteeen** [comment]
it plays haptics to the sound that currently plays

**Comment by Litteeen** [comment]
I just fixed the call connect bug, I will be closing this now, keep an eye open for the new version (should be ready very soon)

**Comment by simba4** [comment]
Ok thanks.


Best regards,

Simeon Sheev
