### ISSUE TITLE
Control with ringer switch

### ISSUE THREAD

**Issue by simba4** [Litteeen/Rose#26]
Make the vib keyboard works with ringers switch- switch to off vibration work, switch to on vibration stop working.

**Comment by Litteeen** [comment]
you mean as an exception?

**Comment by simba4** [comment]
Yes, it will be good if on ringer switch on, when there are sounds and clicks, the vibration to be off and vice versa.

Best regards,

Simeon Sheev

**Comment by Litteeen** [comment]
this is a feature request, send it to my mail
