### ISSUE TITLE
Some of the apps crash

### ISSUE THREAD

**Issue by kingstonckt** [Litteeen/Rose#29]
After turning ROSE on, some of the apps crash, such as snapchat, google photo, icleaner and some of the local bank apps. Thus, please add a function to blacklist apps from applying ROSE functions.

**Comment by Litteeen** [comment]
i’m not going to add blacklisting, but you’re pretty much the only one to have that issue

Try if there’s something else causing it or at least provide a crash log

**Comment by Litteeen** [comment]
Also this issue is a duplicate of an already existing one so i’ll close this one
