### ISSUE TITLE
Always use HapticFeedback

### ISSUE THREAD

**Issue by FellFromTheSky** [Litteeen/Rose#33]
I wouldwant to get HapticFeedback for aything touch on the screen (nothing exist at touched place, keyboards, buttons, text, actions, ...).
Is it foabl with the actual tweak?

**Comment by Litteeen** [comment]
> system wide section

**Comment by FellFromTheSky** [comment]
It's not working at all in iOS 13.5 and the system wide section is even not full touchscreen HapticFeedback since it's limited to some options. What I would want is HapticFeedback for anywhere you touch on the screen, even where there's nothing.

If you need some advices to do it, just take a look to the Haptic TouchScreen tweak in Kiimo repo and edit it in order to fix the "infinite" HapticFeedback bug (you'll know what I,m talking about if you try the tweak).

**Comment by Litteeen** [comment]
support has ended here for you, i don’t support people who pirate tweaks

**Comment by FellFromTheSky** [comment]
I never said I pirated the tweak.

**Comment by Litteeen** [comment]
it was only added to cydia because you used it earlier

**Comment by FellFromTheSky** [comment]
Nope, and as I said, if this repo hosts piracy why is listed in leget repo lists over the web?

**Comment by FellFromTheSky** [comment]
If you want I can remove Kiimo repo.

**Comment by Litteeen** [comment]
even if you’ve downloaded rose from my repo i still don’t give out support for people who pirate at all

kiiimo’s repo is a piracy repo and that’s obvious, it hasn’t ever been a default repo and it won’t ever be

**Comment by FellFromTheSky** [comment]
https://lmgtfy.com/?q=cydia+repo+list+ios+13.5
This is how I found the repos I used.

**Comment by FellFromTheSky** [comment]
@Litteeen 
Then why who someone like me who bought an Apple Developer Membership at $ 99 USD to obtain OS X 10.5 and OS X 10.6 legally would ever need to pirate something for obtaining it?

**Comment by Litteeen** [comment]
you don't have any evidence that you don't have anything installed from pirate repos, i would have requested a package list now but that would be silly as you could just remove the packages before

**Comment by FellFromTheSky** [comment]
Uh nope. Why would I ever lie to a good coder as you?
I'm also a coder, those are two of my works :
[No Cubes Reloaded](https://www.curseforge.com/minecraft/mc-mods/nocubes/files/2856582), that I created practically from scratch with friends.
[The Realistic Leaves Mod](https://www.planetminecraft.com/mod/the-realistic-leaves-mod/), that I created from scratch. By the way, vrackfall is my previous username.

**Comment by Litteeen** [comment]
it doesn't really prove anything to be a programmer yourself, it just makes you look better in that situation, at least in my 16 year old eyes but others could see that differently

also, don't think i want to be unfriendly or anything, just being protective as i had cases where people would request something but obviously pirated, sorry if it looked like it

rose's feature updates have ended three days ago though, i'll only fix things for newer iOS versions etc from now on (https://twitter.com/Litteeen/status/1263765932549328898?s=20)

**Comment by FellFromTheSky** [comment]
@Litteeen 
I'm 20 years old.
I learned programming [at my high school](https://chene-bleu.info/i/ladifference/indexnew.asp) during two discontinuous years. My teacher explecitly siad us that we shouldn't do something that would break our lives, the earth and the whole universe. I'm now in a programming program in college. The college is after high school and before university in Canada.
First time I learned what was Internet, I was thirteen.
First time I jailbroken an iDevice I was fourteen and it was my first iPod ever, an iPod 5.
First time I coded a website, I was fourteen.
First time I played Minecraft I was fourteen and it was on a pretty old Windows XP computer that I installed Linux on it to be able to run the game aat 15 fps.
Want more?
I'm as legit than I always respected parantal control on computer when I was a teen (who ever do it?).

**Comment by FellFromTheSky** [comment]
So if you want I code something for you, I'll certainly do it.

**Comment by Litteeen** [comment]
i have my reasons to be courteous, but i think i trust you now

i also appreciate your willingness to help but i'm better off alone

**Comment by FellFromTheSky** [comment]
Anyway, I never coded in C, C++ nor any C programming languages.
I'm mainly learning how to code by trying things and by experience.
The only one i know are those ones :
DOS
PowerShell
Bash
Oh My Zsh
Python 2 to 3
Java 7 to 14
Kotlin
HTML 4 to 5
CSS 3
PHP 5 to 7
JavaScript
MySQL
Apache2

I also know how to use in real time bytecode editors like Mixin, ASM a [Partial Modification Loader ](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/2602016-partial-modification-loader-pml-10-3-for-minecraft)
Partial Modification is the greatest one because of the way it was coded.
I'm also a friend of his creator, but I didn't talked to him since a while.
